# Generated by Django 5.2.8 on 2025-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '1. Contact Form Leads',
            },
        ),
        migrations.CreateModel(
            name='VisaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('visa_type', models.CharField(choices=[('visa-free', 'Visa-Free'), ('evisa', 'e-Visa'), ('voa', 'Visa on Arrival')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '2. Visa Form Leads',
            },
        ),
    ]
